"""add followers

Revision ID: 32659ac8cce7
Revises: aaa2c9e7f9a9
Create Date: 2021-01-07 08:58:51.982653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32659ac8cce7'
down_revision = 'aaa2c9e7f9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
